// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrmibvylpzlvxnecqigj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZybWlidnlscHpsdnhuZWNxaWdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NjA0MDMsImV4cCI6MjA2OTEzNjQwM30.b9QWR13LWkmfcR01VqUOgG9wdgLcEIx4LhWcagVOdj0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});